# ensure all apps and packages can still build and test
name: Sync dev -> main

env:
    HELIUS_API_KEY: "chewed-glass"

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Merge dev -> mains
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: dev
                target_branch: main
                github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Merge main -> vercel/staging
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: main
                target_branch: vercel/staging
                github_token: ${{ secrets.GITHUB_TOKEN }}
